export default {
    LOGIN: 'LOGIN',
    HOME_DATA: 'HOME_DATA',
    USER_LOGOUT: 'USER_LOGOUT',
    CREATE_TODOITEMS: 'CREATE_TODOITEMS',
    DELETE_TODOITEMS: 'DELETE_TODOITEMS',
    UPDATE_TODOITEMS: 'UPDATE_TODOITEMS'
};